name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    # Other dependencies from hosted runner
    # AWS CLI
    # indirectly node used by actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get go.mod details
      uses: Eun/go-mod-details@v1
      id: go-mod-details
      with: 
        modfile: ${{ github.workspace }}/test/go.mod
    
    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.go-mod-details.outputs.go_version }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.3"

    # - name: Import Secrets
    #   id: secrets
    #   uses: hashicorp/vault-action@v2
    #   with:
    #     url: ${{ secrets.VAULT_ADDR }}
    #     method: approle
    #     roleId: ${{ secrets.VAULT_ROLE_ID }}
    #     secretId: ${{ secrets.VAULT_SECRET_ID }}
    #     exportEnv: false
    #     secrets: |
    #       secret/data/products/infrastructure-experience/ci/common AWS_ACCESS_KEY;
    #       secret/data/products/infrastructure-experience/ci/common AWS_SECRET_KEY;

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        # aws-access-key-id: ${{ steps.secrets.outputs.AWS_ACCESS_KEY }}
        # aws-secret-access-key: ${{ steps.secrets.outputs.AWS_SECRET_KEY }}
        aws-region: eu-west-2

    - name: Terratest Terraform Init And Apply
      working-directory: ./test
      timeout-minutes: 45
      run: |
        go test --count=1 -v -timeout 45m ../test -run TestSetupTerraform

    - name: Terratest Test 2 Region AWS
      working-directory: ./test
      timeout-minutes: 15
      run: |
        go test --count=1 -v -timeout 15m ../test -run Test2RegionAWSEKS

    - name: Terratest Terraform Teardown
      working-directory: ./test
      timeout-minutes: 15
      run: |
        go test --count=1 -v -timeout 15m ../test -run TestTeardownTerraform
